<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1600356629610' stop='1600356880819'>
    <name>Data Driven Suite</name>
    <title>Data Driven Suite</title>
    <test-cases>
        <test-case start='1600356637600' status='passed' stop='1600356649659'>
            <name>Validate appointment booking in CURA Healthcare Service</name>
            <title>Validate appointment booking in CURA Healthcare Service</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1600356649662' status='failed' stop='1600356759974'>
            <name>Validate appointment booking in CURA Healthcare Service</name>
            <title>Validate appointment booking in CURA Healthcare Service</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\APPAN\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:531:17)
                    at processTimers (internal/timers.js:475:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1600356759976' status='failed' stop='1600356880807'>
            <name>Validate appointment booking in CURA Healthcare Service</name>
            <title>Validate appointment booking in CURA Healthcare Service</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\APPAN\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:531:17)
                    at processTimers (internal/timers.js:475:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>